maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn jar:jar -B"
  artifacts:
    paths:
      - target/*.jar
    
test:  

    script:
        - rm public/*
        - mv src/test/resources/reports/coverage/* public/
